### ISSUE TITLE
publish on npm.

### ISSUE THREAD

**Issue by jessy1092** [VikramN/Re-Tag#2]
This is a simple and useful component. Would you publish on npm for reuse easily?

**Comment by VikramN** [comment]
Ok let me give it a shot, never done this before, so it may take time

**Comment by bebraw** [comment]
@VikramN FYI, I wrote a little [guide on the topic](http://www.nixtu.info/2015/02/how-to-publish-and-maintain-npm-packages.html). That might clear some things up. You'll need to set up a `package.json` with basic info. If you want I can do a PR to help you get started.

**Comment by VikramN** [comment]
Thanks. I went thru it. I wanna give this a shot, so I can learn the process. Have a question though.. what about the CSS file that's needed to render the tags? Will users have to manually copy them over?

**Comment by bebraw** [comment]
> what about the CSS file that's needed to render the tags? Will users have to manually copy them over?

In case of Webpack you would do `require('Re-Tag/style.css')` provided there's `style.css` at project root. I think that's a good starting point.

As people use the library you might get better ideas but this is what I've stuck with personally.

**Comment by jessy1092** [comment]
or use inline-style. You can use [react-style](https://github.com/js-next/react-style) to write css-like js with component.

If you don't like to write inline-style, It can place on github release for download traditionally or use [bower](http://bower.io/).

**Comment by VikramN** [comment]
@jessy1092  What about :hover and :before? They docs says they aren't supported?

**Comment by bebraw** [comment]
@VikramN [Radium](http://projects.formidablelabs.com/radium/), a newer approach, supports :hover.

**Comment by jessy1092** [comment]
@bebraw :+1:  good news

**Comment by VikramN** [comment]
Hey guys. 

I've updated the code base and samples. I've moved everything to ReTag namespace of sorts. 

I went thru a lot of react components. I didn't like the complicated packaging and maintenance involved. Check out addDefaultStyles to add css. I took this idea from another react component - felt it was simplest with least issues.

You will need to refresh the demo page (add a  ? if it doesn't). No css file involved in that!

So I have an npm package https://www.npmjs.com/package/re-tag. 
You can - npm install re-tag
It also adds tag.css in case you want it. Let me know if something is left-out / not-working. 

Thanks for all the help & ideas :+1:
